version: '3'
services:
  wordpress:
    build: .
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8
    env_file:
      - .env
    networks:
      - mynetwork
      
redis:
  image: "redis-alpine"
  networks:
    - mynetwork

networks:
  - mynetwork