version: '3'
services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST: db
      - WORDPRESS_DB_USER: barthemweb
      - WORDPRESS_DB_PASSWORD: J!o9s8e2
      - WORDPRESS_DB_NAME: barthemweb
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: 12345
    MYSQL_RANDOM_ROOT_PASSWORD: "1"
    networks:
      - mynetwork
      
redis:
  image: "redis-alpine"
  networks:
    - mynetwork

networks:
  mynetwork